camera:
  device_id: 0
  width: 640
  height: 480
  fps: 30

pose:
  model_path: data/pose_landmarker_full.task
  min_visibility: 0.3

angles:
  smoothing_factor: 0.3

mapping:
  mirror_mode: true
  dead_zone_deg: 3.0

serial:
  port: /dev/tty.usbserial-0001
  baud: 115200

simulation:
  urdf_path: urdf/real_steel.urdf

punch_compensator:
  wrist_rise_threshold: 0.0
  foreshortening_threshold: 0.7
  velocity_threshold: 0.02
  attack_alpha: 0.4
  decay_alpha: 0.3

safety:
  max_velocity: 2.0
  position_tolerance: 0.1
  watchdog_timeout: 2.0
  max_continuous_runtime: 600
